services:
  ssl-proxy:
    image: nginx:alpine
    volumes:
      # Nginxの設定ファイルをマウント
      # server { ... } や upstream { ... } など、httpブロック内で使用するディレクティブのみ。
      # Nginxのデフォルトのメイン設定を維持しつつ、機能（SSL、プロキシ、キャッシュなど）を追加できるため。最も柔軟で安全な方法です。
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 証明書と鍵ファイルをマウント
      - ./certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./certs/server.key:/etc/nginx/certs/server.key:ro
      # 静的ファイルをマウント
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "443:443" # HTTPSの標準ポート443を公開